### PR TITLE
Add MLCompute

### PR DESCRIPTION
**Pull request by AlexanderEkdahl**
Tested using:

``` rust
#[cfg(test)]
mod tests {
    use icrate::MLCompute::MLCDevice;

    #[test]
    fn it_works() {
        unsafe {
            let device = MLCDevice::aneDevice();
            dbg!(device);
        }
    }
}

```

This is a relatively obscure API that is intended to be used by Machine Learning frameworks to efficiently use the Apple hardware.

However, I noticed that I had to add `"Metal_all"` to the `features` when depending on `icrate` or I would get the following error:

<details>
  <summary>Full error</summary>

```
error[E0412]: cannot find type `MTLRenderPipelineReflection` in this scope
   --> /Users/alexanderekdahl/emergence/objc2/crates/icrate/src/Metal/../generated/Metal/MTLDevice.rs:210:14
    |
210 |           *mut MTLRenderPipelineReflection,
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
   ::: /Users/alexanderekdahl/emergence/objc2/crates/icrate/src/Metal/../generated/Metal/MTLRenderPipeline.rs:639:1
    |
639 | / extern_protocol!(
640 | |     pub unsafe trait MTLRenderPipelineState: NSObjectProto...
641 | |         #[cfg(feature = "Foundation_NSString")]
642 | |         #[method_id(@__retain_semantics Other label)]
...   |
718 | |     unsafe impl ProtocolType for dyn MTLRenderPipelineStat...
719 | | );
    | |_- similarly named trait `MTLRenderPipelineState` defined here
    |
help: a trait with a similar name exists
    |
210 |         *mut MTLRenderPipelineState,
    |              ~~~~~~~~~~~~~~~~~~~~~~
help: you might be missing a type parameter
    |
207 | pub type MTLNewRenderPipelineStateWithReflectionCompletionHandler<MTLRenderPipelineReflection> = *mut Block<
    |                                                                  +++++++++++++++++++++++++++++

error[E0412]: cannot find type `MTLComputePipelineReflection` in this scope
   --> /Users/alexanderekdahl/emergence/objc2/crates/icrate/src/Metal/../generated/Metal/MTLDevice.rs:227:14
    |
227 |           *mut MTLComputePipelineReflection,
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
   ::: /Users/alexanderekdahl/emergence/objc2/crates/icrate/src/Metal/../generated/Metal/MTLComputePipeline.rs:205:1
    |
205 | / extern_protocol!(
206 | |     pub unsafe trait MTLComputePipelineState: NSObjectProt...
207 | |         #[cfg(feature = "Foundation_NSString")]
208 | |         #[method_id(@__retain_semantics Other label)]
...   |
263 | |     unsafe impl ProtocolType for dyn MTLComputePipelineSta...
264 | | );
    | |_- similarly named trait `MTLComputePipelineState` defined here
    |
help: a trait with a similar name exists
    |
227 |         *mut MTLComputePipelineState,
    |              ~~~~~~~~~~~~~~~~~~~~~~~
help: you might be missing a type parameter
    |
224 | pub type MTLNewComputePipelineStateWithReflectionCompletionHandler<MTLComputePipelineReflection> = *mut Block<
    |                                                                   ++++++++++++++++++++++++++++++

For more information about this error, try `rustc --explain E0412`.
error: could not compile `icrate` due to 2 previous errors
```

</details>

Requires https://github.com/madsmtm/icrate-generated/pull/7

### CODE REVIEW

**Comment by madsmtm** [comment]
> Tested using

Perhaps you can add that as a test then? Inside `src/MLCompute/mod.rs` is fine.

> However, I noticed that I had to add `"Metal_all"` to the `features` when depending on `icrate` or I would get the following error [snip]

Yeah, the dependency tracking that `header-translator` does is very incomplete, I hope to fix that as part of https://github.com/madsmtm/objc2/issues/448.

**Comment by madsmtm** [comment]
Also, it seems like a lot of this functionality is quite trivial to mark as safe, perhaps I could get you to do that, at least for the most commonly used parts / the parts you need yourself?

**Comment by AlexanderEkdahl** [comment]
> Also, it seems like a lot of this functionality is quite trivial to mark as safe, perhaps I could get you to do that, at least for the most commonly used parts / the parts you need yourself?

I'd be happy to try but I don't think I can be confident as to what constitutes a safe method. The API is large to accommodate all of the building blocks that make up neural networks. If I were to guess all of the graph operators are safe (as it's just specifying the network architecture) and the tensor operations involving data can be unsafe.

**Comment by AlexanderEkdahl** [comment]
Closing this PR as Apple has seemingly deprecated the entire API despite being introduced only 2 years ago... 

https://developer.apple.com/documentation/mlcompute

**Comment by madsmtm** [comment]
Huh, yeah, that was fast...

**Comment by madsmtm** [comment]
I ended up adding this in https://github.com/madsmtm/objc2/commit/5d7f8e0eaf917af9d391ac6d14ddaad423d4c472 as, like you said a few weeks back, Apple hasn't added an alternative to this functionality yet.

**Pull request closed without merging**
